### PR TITLE
feat(migration): Updated to Serenity/JS 3.0.0-rc

### PR DESCRIPTION
**Pull request by viper3400**
@jan-molak 

* I migrated the template according to https://github.com/serenity-js/serenity-js/issues/1160
* Though there is a version 8 of `@cucumber/cucumber` I haven't updated the version as you use `^7.3.2` in the [package](https://github.com/serenity-js/serenity-js/blob/8bd28e99ef21ce0cf44e9c95e64761b0a89196fa/packages/cucumber/package.json#L68]) and I think some other migration steps would be required here. (You may no, I am not the cucumber user at all)

Could you please create a `main` branch in this repository, I will then rebase the changes.

----

**_Fun fact_**: The template uses `services: ['chromedriver']` in it's `wdio.conf.ts`. You can see the [404 error from 1156](https://github.com/serenity-js/serenity-js/issues/1156) with this template, as well. (Until you comment out this line and then forcing wdio to use its default `devtools` I assume.)

### CODE REVIEW

**Comment by viper3400** [comment]
Just noticed the dependency to `@serenity-js/web` is missing in `package.json`. I will add it.

**Comment by viper3400** [comment]
@jan-molak 
* Raised template version to 3.0.0 in `package.json`
* Added dependency to `@serenity-js/web`
* merged update from master back to the feature branch

**Comment by jan-molak** [comment]
I've created `main`, many thanks for the help!

**Comment by jan-molak** [comment]
@viper3400 - would you mind rebasing this PR against `main`? Thanks!

**Pull request merged**
